package org.beigesoft.accounting.persistable;

/*
 * Beigesoft ™
 *
 * Licensed under the Apache License, Version 2.0
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

import org.beigesoft.persistable.AHasNameIdLong;

/**
 * <pre>
 * Model of Warehouse Place e.g. room#1.
 * Nonautogenerated ID is Integer type for best performance
 * cause String is slower
 * </pre>
 *
 * @author Yury Demidenko
 */
public class WarehouseSite extends AHasNameIdLong {

  /**
   * <p>Warehouse.</p>
   **/
  private Warehouse warehouse;

  //Simple getters and setters:
  /**
   * <p>Geter for warehouse.</p>
   * @return Warehouse
   **/
  public final Warehouse getWarehouse() {
    return this.warehouse;
  }

  /**
   * <p>Setter for warehouse.</p>
   * @param pWarehouse reference
   **/
  public final void setWarehouse(final Warehouse pWarehouse) {
    this.warehouse = pWarehouse;
  }
}
